### ISSUE TITLE
podman-git does not build service files

### ISSUE THREAD

**Issue by qubidt** [samarthj/AUR#3]
quoting [my comment on AUR](https://aur.archlinux.org/pkgbase/podman-git#comment-871410):

> `systemd` should be added to `makedepends`. to build the service files (`src/podman/Makefile:791`), it checks for the existence of `systemd/sd-daemon.h` (see `src/podman/hack/systemd_tag.sh`), which is part of `core/systemd`, not `core/systemd-libs` (i.e. `libsystemd` alone in `makedepends` is inadequate).

You won't notice this usually, but when I build in a fresh chroot the files in `contrib/systemd/` aren't included in the package unless you add `systemd` to the `makedepends`.

This might imply that `libsystemd` is unnecessary. I haven't tested that yet.

**Comment by samarthj** [comment]
updated the broken build 6841d2141c8ad2644912814d6e65d18496204da8
