### ISSUE TITLE
[podman-git] firewall rules missing

### ISSUE THREAD

**Issue by Loader009** [samarthj/AUR#6]
Hey there,

according to the podman matrix room, there are firewall rules missing.
According to a friend this is also the case for podman from the archlinux community repo.

Is there anything I am missing?
```
# iptables -nvL
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
```

**Comment by samarthj** [comment]
[Replied](https://aur.archlinux.org/pkgbase/podman-git#comment-881863) to your comment on the AUR for general visiblity. Please have a look.

Closing this as it doesn't sound like you are facing any issue rather just asking a question, but feel free to re-open it, if there is a specific problem with it.
